[package]
name = "voice_hz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13"       # 音訊 I/O
anyhow = "1.0"      # 簡化錯誤處理
